const PDFDocument = require('pdfkit');

const generatePdfTranscript = (data) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });
        let buffers = [];
        
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
            let pdfData = Buffer.concat(buffers);
            resolve(pdfData);
        });
        doc.on('error', reject);

        // --- Styling Constants ---
        const colors = {
            primary: '#1e40af', // Dark Blue
            secondary: '#64748b', // Slate Gray
            text: '#0f172a', // Dark Slate
            lightBg: '#f1f5f9', // Light Gray Background
            border: '#cbd5e1'  // Border Gray
        };
        const fonts = {
            regular: 'Helvetica',
            bold: 'Helvetica-Bold',
            italic: 'Helvetica-Oblique'
        };

        // --- Helper Functions ---
        const drawHeader = () => {
            // Header Bar
            doc.rect(0, 0, doc.page.width, 100).fill(colors.primary);
            
            // Title
            doc.fontSize(28).font(fonts.bold).fill('white')
                .text('OFFICIAL TRANSCRIPT', 50, 40);
            
            // Subtitle
            doc.fontSize(12).font(fonts.regular).fill('white')
                .text('Competency-Based Education Management System', 50, 75);

            // Date on the right
            const date = new Date().toLocaleDateString('en-US', {
                year: 'numeric',
                month: 'long',
                day: 'numeric'
            });
            doc.fontSize(10).text(`Issued: ${date}`, 50, 40, { align: 'right', width: doc.page.width - 100 });
        };

        const drawFooter = () => {
            const range = doc.bufferedPageRange();
            for (let i = range.start; i < range.start + range.count; i++) {
                doc.switchToPage(i);
                
                // Prevent footer from triggering new page by temporarily removing bottom margin
                const oldBottomMargin = doc.page.margins.bottom;
                doc.page.margins.bottom = 0;

                doc.fontSize(8).fill(colors.secondary)
                   .text(
                       `Page ${i + 1} of ${range.count} | Generated by CBE-AMS`,
                       50,
                       doc.page.height - 30,
                       { align: 'center' }
                   );
                
                // Restore bottom margin
                doc.page.margins.bottom = oldBottomMargin;
            }
        };

        const drawSectionHeader = (title, y) => {
            doc.fontSize(16).font(fonts.bold).fill(colors.primary)
               .text(title, 50, y);
            doc.moveTo(50, y + 20).lineTo(doc.page.width - 50, y + 20).strokeColor(colors.border).stroke();
            return y + 35; // Return new Y position
        };

        // --- Content Generation ---

        drawHeader();

        let yPos = 130;

        // Student Details Section
        doc.fontSize(12).font(fonts.bold).fill(colors.text).text('Student Information', 50, yPos);
        yPos += 20;

        // Draw a box for student details
        doc.rect(50, yPos, doc.page.width - 100, 105).strokeColor(colors.border).stroke();
        
        const startX = 60;
        const col2X = 300;
        const rowHeight = 25;
        let textY = yPos + 15;

        // Row 1
        doc.font(fonts.bold).fill(colors.secondary).text('NAME:', startX, textY);
        doc.font(fonts.bold).fill(colors.text).text(data.student.name || 'N/A', startX + 60, textY);
        
        doc.font(fonts.bold).fill(colors.secondary).text('REGISTRATION NO:', col2X, textY);
        doc.font(fonts.bold).fill(colors.text).text(data.student.regNumber || 'N/A', col2X + 120, textY);

        textY += rowHeight;

        // Row 2
        doc.font(fonts.bold).fill(colors.secondary).text('EMAIL:', startX, textY);
        doc.font(fonts.bold).fill(colors.text).text(data.student.email || 'N/A', startX + 50, textY);

        textY += rowHeight;

        // Row 3 (Program on its own line for long names)
        doc.font(fonts.bold).fill(colors.secondary).text('PROGRAM:', startX, textY);
        doc.font(fonts.bold).fill(colors.text).text(data.student.program || 'N/A', startX + 80, textY, { width: doc.page.width - 200 });

        yPos += 125;

        // Check for page break
        const checkPageBreak = (neededHeight) => {
            if (yPos + neededHeight > doc.page.height - 50) {
                doc.addPage();
                yPos = 50; // Reset Y
                return true;
            }
            return false;
        };

        // Module Scores (Yearly Summary)
        checkPageBreak(100);
        yPos = drawSectionHeader('Academic Performance', yPos);

        if (Object.keys(data.yearlySummary).length === 0) {
            doc.fontSize(12).font(fonts.italic).fill(colors.secondary).text('No module records found.', 50, yPos);
            yPos += 20;
        } else {
            // Sort years in descending order
            const sortedYears = Object.keys(data.yearlySummary).sort((a, b) => b - a);

            for (const year of sortedYears) {
                checkPageBreak(100);
                
                // Year Sub-header
                doc.rect(50, yPos, doc.page.width - 100, 25).fill(colors.lightBg);
                doc.fontSize(12).font(fonts.bold).fill(colors.text)
                   .text(`Year ${year}`, 60, yPos + 7);
                doc.fontSize(10).font(fonts.italic).fill(colors.primary)
                   .text(`Average Score: ${data.yearlySummary[year].averageScore}`, 50, yPos + 7, { align: 'right', width: doc.page.width - 110 });
                
                yPos += 30;

                // Table Header
                const tableHeaders = [
                    { label: 'Code', x: 50, w: 80 },
                    { label: 'Module Title', x: 130, w: 250 },
                    { label: 'Score', x: 380, w: 60 },
                    { label: 'Grade', x: 440, w: 100 }
                ];

                doc.font(fonts.bold).fontSize(10).fill(colors.secondary);
                tableHeaders.forEach(h => doc.text(h.label, h.x, yPos));
                doc.moveTo(50, yPos + 15).lineTo(doc.page.width - 50, yPos + 15).strokeColor(colors.border).stroke();
                yPos += 20;

                // Table Rows
                doc.font(fonts.regular).fill(colors.text);
                data.yearlySummary[year].modules.forEach((module, index) => {
                    checkPageBreak(20);
                    
                    // Zebra striping (optional, keeping it simple for now)
                    
                    doc.text(module.moduleCode, tableHeaders[0].x, yPos);
                    doc.text(module.moduleTitle, tableHeaders[1].x, yPos, { width: tableHeaders[1].w, lineBreak: false, ellipsis: true });
                    doc.text(`${module.score}%`, tableHeaders[2].x, yPos);
                    doc.text(module.descriptor, tableHeaders[3].x, yPos);
                    
                    yPos += 15;
                });
                yPos += 20; // Space between years
            }
        }

        // Course Summaries (Competencies)
        checkPageBreak(100);
        yPos = drawSectionHeader('Course & Competency Summary', yPos);

        if (data.courseSummaries.length === 0) {
            doc.fontSize(12).font(fonts.italic).fill(colors.secondary).text('No course summaries available.', 50, yPos);
        } else {
            data.courseSummaries.forEach(course => {
                checkPageBreak(120);

                // Course Card-like styling
                doc.roundedRect(50, yPos, doc.page.width - 100, 60, 5).strokeColor(colors.border).stroke();
                
                // Course Title & Score
                doc.fontSize(12).font(fonts.bold).fill(colors.text)
                   .text(`${course.courseName} (${course.courseCode})`, 60, yPos + 10);
                
                if (course.overallScore !== null && course.overallScore !== undefined) {
                    doc.fontSize(10).font(fonts.bold).fill(colors.primary)
                       .text(`Overall: ${course.overallScore}% - ${course.overallDescriptor}`, 60, yPos + 28);
                }

                yPos += 70;

                // Demonstrated Competencies List
                if (course.demonstratedCompetencies && course.demonstratedCompetencies.length > 0) {
                    doc.fontSize(10).font(fonts.bold).fill(colors.secondary).text('Key Competencies:', 60, yPos);
                    yPos += 15;
                    
                    doc.font(fonts.regular).fill(colors.text);
                    course.demonstratedCompetencies.forEach(comp => {
                        checkPageBreak(15);
                        doc.circle(65, yPos + 4, 2).fill(colors.secondary);
                        doc.text(comp.name, 75, yPos);
                        yPos += 12;
                    });
                    yPos += 10;
                }
                
                yPos += 10; // Extra spacing between courses
            });
        }

        // Finalize
        drawFooter();
        doc.end();
    });
};

module.exports = { generatePdfTranscript };